//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TvShowOfTheYearMessage", Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    [System.SerializableAttribute()]
    public partial class TvShowOfTheYearMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TvShowReviewMessage", Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    [System.SerializableAttribute()]
    public partial class TvShowReviewMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReviewField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Review {
            get {
                return this.ReviewField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewField, value) != true)) {
                    this.ReviewField = value;
                    this.RaisePropertyChanged("Review");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateTvShow", ReplyAction="http://tempuri.org/IService1/CreateTvShowResponse")]
        int CreateTvShow(string name, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateTvShow", ReplyAction="http://tempuri.org/IService1/UpdateTvShowResponse")]
        bool UpdateTvShow(string name, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CloseVoting", ReplyAction="http://tempuri.org/IService1/CloseVotingResponse")]
        bool CloseVoting(int tvShow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OpenVoting", ReplyAction="http://tempuri.org/IService1/OpenVotingResponse")]
        bool OpenVoting(int tvShow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNumberOfVotes", ReplyAction="http://tempuri.org/IService1/GetNumberOfVotesResponse")]
        int GetNumberOfVotes(int tvShow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNumberOfVotesByPeriod", ReplyAction="http://tempuri.org/IService1/GetNumberOfVotesByPeriodResponse")]
        int GetNumberOfVotesByPeriod(int tvShow, System.DateTime from, System.DateTime until);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CanUserStillVote", ReplyAction="http://tempuri.org/IService1/CanUserStillVoteResponse")]
        bool CanUserStillVote(int user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetTvShowOfTheYear", ReplyAction="http://tempuri.org/IService1/SetTvShowOfTheYearResponse")]
        string SetTvShowOfTheYear(ConsoleApplication1.ServiceReference1.TvShowOfTheYearMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddTvShowReview", ReplyAction="http://tempuri.org/IService1/AddTvShowReviewResponse")]
        string AddTvShowReview(ConsoleApplication1.ServiceReference1.TvShowReviewMessage message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ConsoleApplication1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.IService1>, ConsoleApplication1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CreateTvShow(string name, int year) {
            return base.Channel.CreateTvShow(name, year);
        }
        
        public bool UpdateTvShow(string name, int year) {
            return base.Channel.UpdateTvShow(name, year);
        }
        
        public bool CloseVoting(int tvShow) {
            return base.Channel.CloseVoting(tvShow);
        }
        
        public bool OpenVoting(int tvShow) {
            return base.Channel.OpenVoting(tvShow);
        }
        
        public int GetNumberOfVotes(int tvShow) {
            return base.Channel.GetNumberOfVotes(tvShow);
        }
        
        public int GetNumberOfVotesByPeriod(int tvShow, System.DateTime from, System.DateTime until) {
            return base.Channel.GetNumberOfVotesByPeriod(tvShow, from, until);
        }
        
        public bool CanUserStillVote(int user) {
            return base.Channel.CanUserStillVote(user);
        }
        
        public string SetTvShowOfTheYear(ConsoleApplication1.ServiceReference1.TvShowOfTheYearMessage message) {
            return base.Channel.SetTvShowOfTheYear(message);
        }
        
        public string AddTvShowReview(ConsoleApplication1.ServiceReference1.TvShowReviewMessage message) {
            return base.Channel.AddTvShowReview(message);
        }
    }
}
